apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: mta-fbc-8-2-ui-e2e-debug
  namespace: art-mta-tenant
spec:
  application: fbc-mta-8-2
  contexts:
    - description: "Debug: deploy MTA operator and run E2E tests on pre-existing cluster"
      name: application
  resolverRef:
    params:
      - name: url
        value: https://github.com/migtools/mta-tackle2-ui
      - name: revision
        value: use_ocpctl_clusters
      - name: pathInRepo
        value: .tekton/integration-tests/mta-fbc-e2e-debug-pipeline.yaml
    resolver: git
    resourceKind: pipeline
